{
  "_id" : ObjectId("5e53b45ead9912102038c968"),
  "vooId" : 744463,
  "empresa" : { "sigla" : "AZU", "nome" : "AZUL", "nacionalidade" : "BRASILEIRA" },
  "ano" : 2016,
  "mes" : 1,
  "aeroportoOrigem" : { "sigla" : "SBAR", "nome" : "ARACAJU", "uf" : "SE", "regiao" : "NORDESTE", "pais" : "BRASIL", "continente" : "AMÉRICA DO SUL" },
  "aeroportoDestino" : { "sigla" : "SBHT", "nome" : "ALTAMIRA", "uf" : "PA", "regiao" : "NORTE", "pais" : "BRASIL", "continente" : "AMÉRICA DO SUL" },
  "natureza" : "Doméstica",
  "grupoVoo" : "Não-regular",
  "passageiros" : { "pagos" : 301, "gratis" : 0 },
  "carga" : { "paga" : { "kg" : 0, "km" : 0 }, "gratis" : { "kg" : 0, "km" : 0 }, "correio" : { "kg" : 0, "km" : 0 } },
  "ask" : 665874,
  "rpk" : 566181,
  "atk" : 76140.99,
  "rtk" : 46677.01,
  "litrosCombustivel" : 21259,
  "distanciaVoada" : 5643,
  "decolagens" : 3,
  "assentos" : 354,
  "payload" : 40479,
  "horasVoadas" : 8.2,
  "pesoBagagem" : 2240,
}
